server:
  port: 11000
  servlet:
    context-path: /api

spring:
  application:
    name: aidoudong-api-product-web  profiles:
    active:
      - dataSources
      - errorCodeEn
#      - kafka
