server:
  port: 10001
  servlet:
    context-path: /auth # 应用名 localhost:11210/auth
    
spring:
  profiles:
    active:
      - dataSources
  application:
    name: aidoudong-oauth2-server
      
info:
  head: ${spring.application.name}${server.servlet.context-path}:${server.port}
  body: is running
    #项目配置说明，通过http://ip(xxx):端口(xxx)/info进行查询
  app:
    name: ${spring.application.name}
    encoding: UTF-8
    java: 
      source: 1.8
      target: 1.8
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
       #可以关闭指定的端点
    shutdown:
      enabled: false
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    serviceUrl:
      defaultZone: http://admin:123456@localhost:9761/eureka
#      defaultZone: http://admin:123456@peer1:9861/eureka/,http://admin:123456@peer2:9862/eureka/,http://admin:123456@peer3:9863/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    metadata-map:
      zone: http://${eureka.instance.hostname}:${server.port}   # eureka可以理解的元数据，不会影响客户端行为
    lease-renewal-interval-in-seconds: 5
#    status-page-url-path: http://${spring.application.name}:${server.port}/auth/actuator/info
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/auth/actuator/info

