spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:9910
#  sleuth:
#    web:
#      client:
#        enabled: true
#    sampler:
#      probability: 1
#  zipkin:
#    base-url: http://192.168.1.160:9411/ # 指定了 Zipkin 服务器的地址
    
info:
  head: ${spring.application.name}:${server.port}
  body: is running
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
       #可以关闭指定的端点
    shutdown:
      enabled: false
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    serviceUrl:
      defaultZone: http://admin:123456@localhost:9761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    lease-renewal-interval-in-seconds: 5
    
feign: 
  hystrix: 
    enabled: false
    